Repository Xymist/ringsmiths, pull requests merged in 2020-09, with the labels that each got.

#9 Declare variable properly
  dist/product_chooser.js
  dist/product_chooser.js.map
  src/product_chooser.js
Labels: bug

#11 Reset button
  dist/product_chooser.js
  dist/product_chooser.js.map
  src/product_chooser.js
Labels: enhancement

#13 Spec text improvements
  dist/product_chooser.js
  dist/product_chooser.js.map
  src/product_chooser.js
  src/title_case.js
Labels: enhancement

#14 (De)selector
  dist/product_chooser.js
  dist/product_chooser.js.map
  src/product_chooser.js
  src/siblings.js
Labels: enhancement

#16 Restructure repo, include CSS
  .gitignore
  data/fields.json
  dist/product_chooser.css
  dist/product_chooser.js
  dist/product_chooser.js.map
  package.json
  src/product_chooser.js
  src/siblings.js
  src/title_case.js
  styles/product_chooser.css
Labels: enhancement

#17 Added core engraving file.
  src/engraving.js
Labels: enhancement

#18 Invisible Next Button
  .flowconfig
  .github/workflows/tests.yml
  data/fields.json
  data/fonts.json
  dist/engraving_main.js
  dist/product_chooser.js
  dist/product_chooser_main.css
  dist/product_chooser_main.js
  package.json
  src/engraving.js
  src/engraving_main.js
  src/product_chooser_main.js
  src/siblings.js
  src/title_case.js
Labels: enhancement

#22 Style changes
  src/product_chooser/finalise_button.jsx
  src/product_chooser/product_choice.jsx
  src/product_chooser/product_result.jsx
  styles/product_chooser.scss
Labels: enhancement, to be tested

#25 Style Changes 2 upload
  dist/product_chooser/product_chooser_main.css
  dist/product_chooser/product_chooser_main.js
  src/product_chooser/product_result.jsx
  styles/product_chooser.scss
Labels: enhancement

#21 React UI
  .babelrc
  .flowconfig
  .gitignore
  README.md
  data/fields.json
  data/product_chooser_fields.json
  dev/index.html
  dist/product_chooser/product_chooser_main.css
  dist/product_chooser/product_chooser_main.js
  dist/product_chooser_main.css
  dist/product_chooser_main.js
  dist/product_page/engraving_main.js
  flow-typed/npm/@babel/core_vx.x.x.js
  flow-typed/npm/@babel/preset-env_vx.x.x.js
  flow-typed/npm/@babel/preset-react_vx.x.x.js
  flow-typed/npm/@reduxjs/toolkit_vx.x.x.js
  flow-typed/npm/cssnano_vx.x.x.js
  flow-typed/npm/flow-bin_v0.x.x.js
  flow-typed/npm/flow-typed_vx.x.x.js
  flow-typed/npm/parcel-bundler_vx.x.x.js
  flow-typed/npm/react-dom_v16.x.x.js
  flow-typed/npm/react-redux_v7.x.x.js
  flow-typed/npm/redux-devtools_vx.x.x.js
  package.json
  src/product_chooser/finalise_button.jsx
  src/product_chooser/next_button.jsx
  src/product_chooser/previous_button.jsx
  src/product_chooser/product_choice.jsx
  src/product_chooser/product_chooser_main.jsx
  src/product_chooser/product_option.jsx
  src/product_chooser/product_result.jsx
  src/product_chooser/reset_button.jsx
  src/product_chooser_main.js
  src/product_page/engraving_main.js
  src/redux_store/product_chooser_slice.js
  src/redux_store/store.js
  src/siblings.js
  src/utils/image_url.js
  src/utils/title_case.js
  styles/product_chooser.css
  styles/product_chooser.scss
Labels: enhancement, help wanted

#26 Un-nest paragraphs
  dist/product_chooser/product_chooser_main.js
  src/product_chooser/product_result.jsx
Labels: bug

#27 Style changes 3 - centre final button and text sizing
  dist/product_chooser/product_chooser_main.css
  dist/product_chooser/product_chooser_main.js
  src/product_chooser/finalise_button.jsx
  src/product_chooser/product_result.jsx
  styles/product_chooser.scss
Labels: enhancement

#28 Style changes 4 Fix margin on P spect text tags and set height on .pr…
  dist/product_chooser/product_chooser_main.css
  styles/product_chooser.scss
Labels: enhancement

#30 Style changes 6, changing .product option height to 100%
  dist/product_chooser/product_chooser_main.css
  styles/product_chooser.scss
Labels: enhancement

#31 Please for the love of god, scale properly on the final product image
  dist/product_chooser/product_chooser_main.css
  styles/product_chooser.scss
Labels: enhancement

#32 Spec Text Fixed.
  dist/product_chooser/product_chooser_main.css
  styles/product_chooser.scss
Labels: bug

#34 Mobile result
  dist/product_chooser/product_chooser_main.js
  src/product_chooser/mobile/mobile_product_result.jsx
  src/product_chooser/product_result.jsx
  src/utils/image_url.js
Labels: bug, help wanted

#35 Add directional arrows to product options
  dist/product_chooser/product_chooser_main.js
  src/product_chooser/mobile/mobile_product_option.jsx
  src/utils/image_url.js
Labels: enhancement

#38 Remove single option display
  dist/product_chooser/product_chooser_main.js
  package.json
  src/product_chooser/mobile/mobile_product_choice.jsx
  src/product_chooser/mobile/mobile_product_option.jsx
  src/redux_store/product_chooser_slice.js
  styles/product_chooser.scss
Labels: enhancement
